name: Create package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version: <major>.<minor>.<patch>'
        required: true

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:

    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install semver
      run: |
        sudo npm i -g semver

    - name: Validate version
      run: |
        semver ${{ github.event.inputs.version }}
        if [ $? != 0 ]; then exit 1; fi

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "TestCategory!=Integration"

    - name: Pack `W4k.Extensions.Configuration.Aws.SecretsManager`
      run: dotnet pack --no-build --configuration Release -p:Version=${{ github.event.inputs.version }} -o artifacts

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: w4k-extensions-configuration-aws-secretsmanager-${{ github.event.inputs.version }}
        path: artifacts/*.nupkg
